export const GET_LIST_PENDING = "GET_LIST_PENDING";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAILURE = "GET_LIST_FAILURE";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";